exclude:
  - script
  - docs
  - vendor

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Drakecb
name: Drakecb
description: 从事前端，爱研究，爱猫

github: https://github.com/cbpi
twitter: https://twitter.com/pii0918
weibo: https://weibo.com/bo0918
email: chenbo9018@mail.com

rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  
baidu_id: 96715dc203611cdcb5539a15664fe630

google_id: UA-120619613-1